server:
  port: 9096

spring:
  application:
    name: config-service
  cloud:
    config:
      server:
        git:
          uri: https://github.com/ArturSydor/config-server
          clone-on-start: true
